CREATE TABLE Persona (
  idPersona INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(20) NULL,
  Paterno VARCHAR(20) NULL,
  Materno VARCHAR(20) NULL,
  Sexo CHAR(1) NULL,
  DNI NUMERIC(8) NULL,
  Celular NUMERIC(9) NULL,
  Direccion VARCHAR(45) NULL,
  PRIMARY KEY(idPersona)
);

CREATE TABLE Usuario (
  idUsuario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idPersona INTEGER UNSIGNED NOT NULL,
  Usuario INTEGER UNSIGNED NULL,
  Clave INTEGER UNSIGNED NULL,
  PRIMARY KEY(idUsuario)
);


